// <auto-generated />
using System;
using ApiEmprendimiento.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiEmprendimiento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250816034222_ActualizarRelacionEmprendimientoInventario")]
    partial class ActualizarRelacionEmprendimientoInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiEmprendimiento.Models.DetalleVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("EmprendimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaVenta")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.Emprendimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Emprendimientos");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.Inventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("EmprendimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmprendimientoId")
                        .IsUnique();

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostoFabricacion")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmprendimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InventarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmprendimientoId");

                    b.HasIndex("InventarioId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("EmprendimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EmprendimientoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.DetalleVenta", b =>
                {
                    b.HasOne("ApiEmprendimiento.Models.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiEmprendimiento.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.Inventario", b =>
                {
                    b.HasOne("ApiEmprendimiento.Models.Emprendimiento", "Emprendimiento")
                        .WithOne("Inventario")
                        .HasForeignKey("ApiEmprendimiento.Models.Inventario", "EmprendimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emprendimiento");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.Producto", b =>
                {
                    b.HasOne("ApiEmprendimiento.Models.Emprendimiento", "Emprendimiento")
                        .WithMany("Productos")
                        .HasForeignKey("EmprendimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiEmprendimiento.Models.Inventario", "Inventario")
                        .WithMany("Productos")
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.Usuario", b =>
                {
                    b.HasOne("ApiEmprendimiento.Models.Emprendimiento", "Emprendimiento")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmprendimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.Emprendimiento", b =>
                {
                    b.Navigation("Inventario")
                        .IsRequired();

                    b.Navigation("Productos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.Inventario", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ApiEmprendimiento.Models.Producto", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
